version: '3'

volumes:
  database_volume:
  static_volume:
  media_volume:

services:
  database:
    image: postgres:10
    env_file:
      - config/db/database_env
    volumes:
      - database_volume:/var/lib/postgresql/data

    ports:
      - 5432:5432

  djangoapp:
    build: .
    volumes:
      - .:/django_introduction/src
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - database

  nginx:
    image: nginx:1.15

    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - djangoapp