# Generated by Django 2.1.4 on 2019-01-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('economy', 'economy'), ('business', 'business'), ('comfort', 'comfort')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
