# Generated by Django 2.1.4 on 2019-01-22 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0002_auto_20190122_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2019, 1, 22, 14, 34, 3, 58298)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2019, 1, 22, 14, 34, 13, 577744)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
