# Generated by Django 2.1.4 on 2019-01-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0002_auto_20190108_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='railways.Route'),
        ),
    ]
