# Generated by Django 2.1.4 on 2019-07-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0003_auto_20190122_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='amount',
            new_name='cost',
        ),
    ]
